### ISSUE TITLE
"Invalid Exclude" warnings when added to Xcode 13 Beta

### ISSUE THREAD

**Issue by wqoq** [mtgto/Unrar.swift#3]
I'm getting the following warnings when adding this package to a project in Xcode Beta 13:

```
Invalid Exclude '.../SourcePackages/checkouts/Unrar.swift/Sources/Cunrar/arcmem.hpp': File not found.
Invalid Exclude '.../SourcePackages/checkouts/Unrar.swift/Sources/Cunrar/arcmem.cpp': File not found.
```

My understanding is that it's because "arcmem.cpp" and "arcmem.hpp" are listed in the `exclude` section for the "Cunrar" target in `Package.swift`, but those files are not in the package.

**Comment by mtgto** [comment]
> My understanding is that it's because "arcmem.cpp" and "arcmem.hpp" are listed in the exclude section for the "Cunrar" target in Package.swift, but those files are not in the package.

Thanks for your report! I released [v0.3.7](https://github.com/mtgto/Unrar.swift/releases/tag/0.3.7).
