### ISSUE TITLE
Include C parts as a pre-compiled library

### ISSUE THREAD

**Issue by shaps80** [mtgto/Unrar.swift#4]
Hi, I was wanting to use this library as a part of my project which I’m currently working on (on holiday) using Swift Playgrounds on iPad.

But obviously anything C++ related can’t be compiled there, while the Swift package imports fine otherwise.

Any chance it’d be possible (I don’t know enough to know if this is even possible) to have the C++ parts available as pre-compiled and included such that _they_ don’t require compilation?

Perhaps this isn’t possible but thought I’d ask on the off-chance, given this is a great little lib and tbh the nicest one I’ve come across personally.

Thanks for your contributions to OSS @mtgto 👍🏻

**Comment by mtgto** [comment]
@shaps80 Sorry for late reply.
I don't have iPad, I somehow build xcframework. Can you test it?

```
url: "https://github.com/mtgto/Unrar.swift"
branch: "binary-target"
```

This branch uses Cunrar binary version for now.

**Comment by shaps80** [comment]
Wow amazing. I will re-test tonight.

**Comment by shaps80** [comment]
@mtgto so on iPad playgrounds you can't point to a branch. It has to be an actual release annoyingly.

**Comment by shaps80** [comment]
![image](https://user-images.githubusercontent.com/251310/167296779-2cf663b7-7713-4f5a-a1aa-339f59ee6406.jpeg)

For your reference this is the UI that allows me to pick the product. So if you had a pre-compiled product available, I could select that and it would allow you to have both. Personally in most 3rd party libs I use the precompiled ones to speed up compile time etc.

So would perhaps be a nice addition for you anyway? @mtgto

**Comment by mtgto** [comment]
@shaps80 Can you choose "binary-target" branch, not "0.3.9" ?
v0.3.9 is past released tag, which does not support binary target.

**Comment by mtgto** [comment]
Create new tag "0.2.1" from branch "binary-target".
https://github.com/mtgto/Unrar.swift/releases/tag/0.2.1

Can you choose 0.2.1? @shaps80

**Comment by shaps80** [comment]
0.2.1? An older version? That seems to have the same issue with clang. Hmm

**Comment by mtgto** [comment]
0.2.1 is only copy from binary-target branch. (= v0.3.x compatible)
https://github.com/mtgto/Unrar.swift/blob/0.2.1/Package.swift uses v0.3.9 precompiled binary.

**Comment by shaps80** [comment]
> 0.2.1? An older version? That seems to have the same issue with clang. Hmm

Actually I get a fatalError in the playgrounds app annoyingly. No other info I'm afraid. Pity.

**Comment by mtgto** [comment]
omg... 😢

**Comment by shaps80** [comment]
Yeah every other version 'works' as in I can at least add the package. Just not compile. But that version fatalError with no error message which sucks.

**Comment by shaps80** [comment]
Oh I can see you used 5.6 in the manifest. I don't think playgrounds on ipad is above 5.5 yet iirc. @mtgto

**Comment by shaps80** [comment]
Actually you mention 5.6 in a file but the manifest is actually 5.3. Can you try setting this to 5.5?

**Comment by mtgto** [comment]
> Oh I can see you used 5.6 in the manifest. I don't think playgrounds on ipad is above 5.5 yet iirc.

Hmm, Package.swift says "// swift-tools-version:5.3"
and I don't the way to set manifest version less than or equal to 5.5.
https://github.com/mtgto/Unrar.swift/blob/0.2.1/Package.swift#L1
I don't found "5.6" text in Cunrar.xcframework.

I examine how to set manifest version. Give me a time.

**Comment by shaps80** [comment]
In that comment at the top of the file you just have to rename it to 5.5 then recreate the xcframeeork (so the signing works). But yep no rush. Appreciate you taking a look.

**Comment by shaps80** [comment]
Or perhaps you mean you'd still like to support 5.3. 

Perhaps it's not working on iOS side tbh. 

https://developer.apple.com/forums/thread/698119

I'll try and find another package with a binary target. See if a similar issue occurs.

**Comment by shaps80** [comment]
Hmm so Intercom uses a binary target and while it doesn't return fatalError, I just get an infinite spinner until it times out.

That is also using Swift 5.3 in its manifest. So I'm not sure if that is the issue or if its a Playgrounds issue. Trying to find a Swift 5.5 manifest with a binary target.

👍

**Comment by shaps80** [comment]
Btw, https://github.com/Alamofire/Alamofire is a good example of how to include multiple Manifest's to back-support older Swift package versions (if you need that)

**Comment by mtgto** [comment]
I create new 0.2.2 tag, which set swift-tools-version 5.5.
https://github.com/mtgto/Unrar.swift/releases/tag/0.2.2

I test 0.2.2 with my iPhone 11 (iOS 15.4.1) and iOS Simulator, and it works fine.

**Comment by shaps80** [comment]
Ok great. I'll test this later tonight. If it doesn't work it must be the playgrounds app. Hopefully it works 👌

Thank you for taking a look at this.

**Comment by shaps80** [comment]
Ok, nope it didn't work unfortunately but I think this is an iPad Playgrounds issue, not yours. Sucks!

Oh well, appreciate you trying and its awesome that you'll now have an binary-target available anyway 👍🏻
